#!/bin/sh

cd /usr/src
git clone https://github.com/rtucker/munin-plugins.git

ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_budlight_if_2
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_budlight_if_3
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_budlight_if_1
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_budlight_if_4
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_budlight_if_5
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_budlight_if_err_2
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_budlight_if_err_1
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_budlight_if_err_3
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_budlight_if_err_4
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_budlight_if_err_5
ln -s /usr/share/munin/plugins/snmp__if_multi       /etc/munin/plugins/snmp_budlight_if_multi
ln -s /usr/share/munin/plugins/snmp__netstat        /etc/munin/plugins/snmp_budlight_netstat
ln -s /usr/share/munin/plugins/snmp__uptime         /etc/munin/plugins/snmp_budlight_uptime
ln -s /usr/share/munin/plugins/snmp__cpuload        /etc/munin/plugins/snmp_coors_cpuload
ln -s /usr/share/munin/plugins/snmp__df             /etc/munin/plugins/snmp_coors_df
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_1
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_10
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_11
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_12
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_13
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_14
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_15
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_16
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_17
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_18
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_19
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_2
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_20
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_21
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_22
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_23
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_24
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_25
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_26
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_27
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_28
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_29
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_3
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_30
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_31
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_32
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_33
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_34
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_35
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_36
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_37
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_4
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_45
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_5
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_6
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_7
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_8
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_coors_if_9
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_1
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_10
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_11
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_12
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_13
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_14
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_15
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_16
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_17
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_18
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_19
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_2
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_20
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_21
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_22
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_23
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_24
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_25
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_26
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_27
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_28
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_29
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_3
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_30
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_31
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_32
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_33
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_34
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_35
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_36
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_37
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_4
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_45
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_5
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_6
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_7
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_8
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_coors_if_err_9
ln -s /usr/share/munin/plugins/snmp__if_multi       /etc/munin/plugins/snmp_coors_if_multi
ln -s /usr/share/munin/plugins/snmp__netstat        /etc/munin/plugins/snmp_coors_netstat
ln -s /usr/share/munin/plugins/snmp__rdp_users      /etc/munin/plugins/snmp_coors_rdp_users
ln -s /usr/share/munin/plugins/snmp__swap           /etc/munin/plugins/snmp_coors_swap
ln -s /usr/share/munin/plugins/snmp__uptime         /etc/munin/plugins/snmp_coors_uptime
ln -s /usr/share/munin/plugins/snmp__winload        /etc/munin/plugins/snmp_coors_winload
ln -s /usr/share/munin/plugins/snmp__winmem         /etc/munin/plugins/snmp_coors_winmem
ln -s /usr/share/munin/plugins/snmp__cpuload        /etc/munin/plugins/snmp_hap-487f95_cpuload
ln -s /usr/share/munin/plugins/snmp__df             /etc/munin/plugins/snmp_hap-487f95_df
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_1
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_2
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_3
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_4
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_5
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_6
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_7
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_8
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-487f95_if_9
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_1
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_2
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_3
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_4
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_5
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_6
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_7
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_8
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-487f95_if_err_9
ln -s /usr/share/munin/plugins/snmp__if_multi       /etc/munin/plugins/snmp_hap-487f95_if_multi
ln -s /usr/share/munin/plugins/snmp__netstat        /etc/munin/plugins/snmp_hap-487f95_netstat
ln -s /usr/share/munin/plugins/snmp__rdp_users      /etc/munin/plugins/snmp_hap-487f95_rdp_users
ln -s /usr/share/munin/plugins/snmp__swap           /etc/munin/plugins/snmp_hap-487f95_swap
ln -s /usr/share/munin/plugins/snmp__uptime         /etc/munin/plugins/snmp_hap-487f95_uptime
ln -s /usr/share/munin/plugins/snmp__winload        /etc/munin/plugins/snmp_hap-487f95_winload
ln -s /usr/share/munin/plugins/snmp__winmem         /etc/munin/plugins/snmp_hap-487f95_winmem
ln -s /usr/share/munin/plugins/snmp__cpuload        /etc/munin/plugins/snmp_hap-ce2580_cpuload
ln -s /usr/share/munin/plugins/snmp__df             /etc/munin/plugins/snmp_hap-ce2580_df
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_1
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_2
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_3
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_4
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_5
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_6
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_7
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_8
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_hap-ce2580_if_9
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_1
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_2
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_3
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_4
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_5
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_6
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_7
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_8
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_hap-ce2580_if_err_9
ln -s /usr/share/munin/plugins/snmp__if_multi       /etc/munin/plugins/snmp_hap-ce2580_if_multi
ln -s /usr/share/munin/plugins/snmp__netstat        /etc/munin/plugins/snmp_hap-ce2580_netstat
ln -s /usr/share/munin/plugins/snmp__rdp_users      /etc/munin/plugins/snmp_hap-ce2580_rdp_users
ln -s /usr/share/munin/plugins/snmp__swap           /etc/munin/plugins/snmp_hap-ce2580_swap
ln -s /usr/share/munin/plugins/snmp__uptime         /etc/munin/plugins/snmp_hap-ce2580_uptime
ln -s /usr/share/munin/plugins/snmp__winload        /etc/munin/plugins/snmp_hap-ce2580_winload
ln -s /usr/share/munin/plugins/snmp__winmem         /etc/munin/plugins/snmp_hap-ce2580_winmem
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_milwaukees-best_if_1
ln -s /usr/share/munin/plugins/snmp__if_            /etc/munin/plugins/snmp_milwaukees-best_if_2
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_milwaukees-best_if_err_1
ln -s /usr/share/munin/plugins/snmp__if_err_        /etc/munin/plugins/snmp_milwaukees-best_if_err_2
ln -s /usr/share/munin/plugins/snmp__if_multi       /etc/munin/plugins/snmp_milwaukees-best_if_multi
ln -s /usr/share/munin/plugins/snmp__netstat        /etc/munin/plugins/snmp_milwaukees-best_netstat
ln -s /usr/share/munin/plugins/snmp__print_pages    /etc/munin/plugins/snmp_milwaukees-best_print_pages
ln -s /usr/share/munin/plugins/snmp__swap           /etc/munin/plugins/snmp_milwaukees-best_swap
ln -s /usr/share/munin/plugins/snmp__uptime         /etc/munin/plugins/snmp_milwaukees-best_uptime

ln -s /munin-plugins/mikrotikcapsman_               /etc/munin/plugins/mikrotikcapsman_coors
ln -s /munin-plugins/mikrotikcpu_                   /etc/munin/plugins/mikrotikcpu_coors
ln -s /munin-plugins/mikrotikcpu_                   /etc/munin/plugins/mikrotikcpu_hap-487f95
ln -s /munin-plugins/mikrotikcpu_                   /etc/munin/plugins/mikrotikcpu_hap-ce2580
ln -s /munin-plugins/mikrotikdiskspace_             /etc/munin/plugins/mikrotikdiskspace_coors
ln -s /munin-plugins/mikrotikdiskspace_             /etc/munin/plugins/mikrotikdiskspace_hap-487f95
ln -s /munin-plugins/mikrotikdiskspace_             /etc/munin/plugins/mikrotikdiskspace_hap-ce2580
ln -s /munin-plugins/mikrotikmemory_                /etc/munin/plugins/mikrotikmemory_coors
ln -s /munin-plugins/mikrotikmemory_                /etc/munin/plugins/mikrotikmemory_hap-487f95
ln -s /munin-plugins/mikrotikmemory_                /etc/munin/plugins/mikrotikmemory_hap-ce2580
ln -s /munin-plugins/mikrotiktemperature_           /etc/munin/plugins/mikrotiktemperature_coors
ln -s /munin-plugins/mikrotiktemperature_           /etc/munin/plugins/mikrotiktemperature_hap-487f95
ln -s /munin-plugins/mikrotiktemperature_           /etc/munin/plugins/mikrotiktemperature_hap-ce2580
ln -s /munin-plugins/mikrotikvoltage_               /etc/munin/plugins/mikrotikvoltage_coors
ln -s /munin-plugins/mikrotikvoltage_               /etc/munin/plugins/mikrotikvoltage_hap-487f95
ln -s /munin-plugins/mikrotikvoltage_               /etc/munin/plugins/mikrotikvoltage_hap-ce2580
ln -s /munin-plugins/ping6_                         /etc/munin/plugins/ping6_ipv6.google.com
ln -s /munin-plugins/ping6_                         /etc/munin/plugins/ping6_mirror.anl.gov
